name: Mutation Testing

on:
  push: ~
  pull_request: ~
  schedule:
    - cron: '0 12 * * *'

jobs:
  test:
    name: Stryker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.7.0
      - name: Install
        run: npm install
      - name: Run Stryker
        run: npm run test:mut
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}
